-- Ślad po korektach godzin (zakładka "Zatwierdzanie zmian").
-- Pisze tu WYŁĄCZNIE resolveCorrection() z utils/corrections.ts.
--
-- shift_id i issue_id są świadomie text, NIE uuid z FK — pierwsza próba
-- z prawdziwym kluczem obcym padła na niezgodność typów (błąd #13), a żadna
-- tabela w tym projekcie i tak nie ma FK.

create table shift_edits (
  id bigint generated by default as identity primary key,
  shift_id text,
  issue_id text,
  editor_name text,
  reason text,
  old_date date,
  old_lokal text,
  old_stanowisko text,
  old_start_time text,
  old_end_time text,
  new_date date,
  new_lokal text,
  new_stanowisko text,
  new_start_time text,
  new_end_time text,
  source text,                         -- 'correction_approved' | 'correction_adjusted'
  created_at timestamptz default now()
);

alter table shift_edits enable row level security;
create policy "open access" on shift_edits for all using (true) with check (true);

-- weryfikacja
select count(*) as kolumn from information_schema.columns
where table_schema = 'public' and table_name = 'shift_edits';
