-- Zadania, log ich wykonania i wnioski o wolne.
-- Odtworzone ze zrzutu produkcji (2026-09-07).

create table tasks (
  id uuid primary key default gen_random_uuid(),
  lokal text not null,
  title text not null,
  description text,
  -- ⚠️ default w bazie to 'poranne', choć formularz od 2026-09-03 podpowiada
  -- 'ogolne'. Kod zawsze wysyła wartość jawnie, więc default nie ma znaczenia
  -- — ale nie opieraj się na nim w niczym nowym.
  schedule_type text not null default 'poranne'::text,
  cycle_days integer,                  -- tylko dla 'cykliczne'
  day_of_week integer,                 -- STARE, zastąpione przez days_of_week
  scope text not null default 'lokal'::text,   -- NIEUŻYWANE od 2026-09-04
  stanowisko text,                     -- NULL = wszyscy; decyduje o widoczności
  owner_label text,                    -- usunięte z UI 2026-09-04, kolumna zostaje
  deadline_time time,
  for_manager boolean not null default false,
  active boolean not null default true,
  archived boolean not null default false,
  created_at timestamptz not null default now(),
  source_issue_id text,                -- luźne odwołanie do issues.id
  days_of_week text,                   -- "1,2,3,4,5", 0=niedziela..6=sobota
  priority text not null default 'sredni'::text
);
alter table tasks enable row level security;
create policy "tasks_open_all" on tasks for all using (true) with check (true);

-- Brak wiersza = niezrobione. Wykonanie jest ZAWSZE wspólne, jeden wiersz na
-- (zadanie, dzień) — ochrona przed dublem żyje w utils/tasks.ts, nie w SQL-u.
create table task_completions (
  id bigint generated by default as identity primary key,
  task_id text not null,               -- luźne odwołanie do tasks.id
  date date not null,
  user_id text,
  user_name text,
  completed_at timestamptz not null default now(),
  shift_id text
);
alter table task_completions enable row level security;
create policy "task_completions_open_all" on task_completions for all using (true) with check (true);

create table absences (
  id uuid primary key default gen_random_uuid(),
  user_id uuid,
  user_name text,
  lokal text,
  start_date date not null,
  end_date date not null,
  type text not null default 'urlop'::text,     -- 'urlop' | 'niedostepnosc'
  status text not null default 'pending'::text, -- 'pending' | 'approved' | 'rejected'
  note text,
  requested_by text,                   -- 'employee' | 'manager'
  decided_by text,
  decided_at timestamptz,
  created_at timestamptz not null default now()
);
alter table absences enable row level security;
create policy "open" on absences for all using (true) with check (true);

-- weryfikacja
select table_name, count(*) as kolumn
from information_schema.columns
where table_schema = 'public' and table_name in ('tasks', 'task_completions', 'absences')
group by table_name order by table_name;
